Document need for pyscopg dependency
Without this, you get this error:

```
Collecting psycopg2-binary==2.8.5
  Using cached psycopg2-binary-2.8.5.tar.gz (381 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running egg_info
      creating /private/var/folders/r4/mb3xl_b96p37yx8fknh1dcdw0000gq/T/pip-pip-egg-info-zjdn8b98/psycopg2_binary.egg-info
      writing /private/var/folders/r4/mb3xl_b96p37yx8fknh1dcdw0000gq/T/pip-pip-egg-info-zjdn8b98/psycopg2_binary.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/r4/mb3xl_b96p37yx8fknh1dcdw0000gq/T/pip-pip-egg-info-zjdn8b98/psycopg2_binary.egg-info/dependency_links.txt
      writing top-level names to /private/var/folders/r4/mb3xl_b96p37yx8fknh1dcdw0000gq/T/pip-pip-egg-info-zjdn8b98/psycopg2_binary.egg-info/top_level.txt
      writing manifest file '/private/var/folders/r4/mb3xl_b96p37yx8fknh1dcdw0000gq/T/pip-pip-egg-info-zjdn8b98/psycopg2_binary.egg-info/SOURCES.txt'
      
      Error: pg_config executable not found.
      
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
      
          python setup.py build_ext --pg-config /path/to/pg_config build ...
      
      or with the pg_config option in 'setup.cfg'.
      
      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.
      
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```